#{
  import "@preview/wut-thesis:0.1.1": wut-thesis, acknowledgements, figure-outline, table-outline, appendix
  import "utils.typ": flex-caption-styles, todo, glossary-outline
  import "glossary.typ": glossary
  import "@preview/glossarium:0.5.8": make-glossary, register-glossary
  import "@preview/drafting:0.2.2": note-outline, set-margin-note-defaults

  show: make-glossary
  register-glossary(glossary)
  show: flex-caption-styles


  /** Drafting

    The "draft" variable is used to change the coloring of links, show TODOs (both in
    the thesis and TODO outline), as well as DRAFT in the header and the title. This
    should be true until the final version is handed-in.

    The "in-print" variable is used to generate a PDF file for physical printing (it adds
    bigger margins on the binding part of the page and changes the numbering placement).
    It should be set to `false` unless you want to create a version of the PDF file for
    physical print, in which case set it to `true`. To prepare a PDF file for the
    final hand-in (that is to upload it to APD/onedrive) please set this variable to
    `false`. variable to false.

  **/
  let draft = true
  let in-print = false
  set-margin-note-defaults(hidden: not draft)

  /// Set the languages of your studies and thesis.
  let lang = (
    /// Language in which you studied, influences the language of the titlepage.
    studies: "pl",
    /// Language in which your thesis is written, influences the rest of the text (i.e.
    /// abstracts order, captions/references supplements, hyphenation etc).
    thesis: "pl"
  )

  show: wut-thesis.with(
    draft: draft,
    in-print: in-print,
    lang: lang,
    // Adjust the following fields accordingly to your thesis
    titlepage-info: (
      thesis-type: "engineer", // or "bachelor" or "master"
      program: "Informatyka",
      specialisation: "Sztuczna Inteligencja",
      institute: "Instytut Informatyki",
      supervisor: "dr inż. Krystian Radlak",
      // The optional advisor of the thesis, this will be typeset as
      //  `consultation`/`konsultacje` in the titlepage.
      advisor: "dr inż. Krystian Radlak", // or `none` if there were no advisors
      faculty: "weiti", // see the tutorial section of this thesis for a list of all possible faculty shorthands
      index-number: "325215",
      date: datetime.today(), // not today: datetime(year: 1969, month: 9, day: 6,)
    ),
    // if you don't want to create a title page (e.g. if you need to use the one
    // generated by APD) then comment the above `titlepage-info` lines and instead
    // uncomment this line:
    // titlepage-info: none,
    author: "Filip Ryniewicz",
    // Note that regardless of the language of your thesis you need to fill in all the
    // fields below - both *.en and *.pl
    title: (
      en: "Application of computer vision methods for automatic assessment of truthfulness",
      pl: "Zastosowanie metod widzenia komputerowego do automatycznej oceny prawdomówności",
    ),
    abstract: (
      en: [
        The aim of the thesis was to examine the effectiveness of computer vision methods in the automatic assessment of veracity based on video recording analysis. The thesis presents various approaches to the problem and describes the development of a tool enabling machine learning model inference on recordings provided by the end user.
        
        The research utilized two datasets: the Silesian Deception Detection Dataset and the Real-Life Deception Detection Dataset. Tools from libraries such as MediaPipe, OpenCV, and FacialEmotionRecognition were used for feature extraction from video recordings, including facial landmarks, optical flow, and emotion probabilities.

        Three modeling approaches were considered: the classic Random Forest machine learning algorithm, a 3D Convolutional Neural Network (3D-CNN), and the ultimately selected bidirectional recurrent GRU network with an attention mechanism. Extensive feature engineering and transfer learning techniques (pre-training on one dataset and fine-tuning on another) were employed in the training process to improve the model's generalization capabilities.

        The conducted experiments showed that the Random Forest model allowed for the identification of the most prominent behavioral features accompanying deception (e.g., eye movements), while the recurrent network achieved promising results in time series analysis, reaching an AUC of 0.63 on the Silesian dataset, which exceeds the detection capabilities of an average human.

        An integral part of the thesis is a web application developed in the Streamlit framework, allowing the user to upload a video file and receive the model's prediction. The results suggest that computer vision methods can support the credibility assessment process; however, potential practical applications require high-quality, representative training data.
      ],
      pl: [
        Celem pracy było zbadanie skuteczności metod wizji komputerowej w automatycznej ocenie prawdomówności osób na podstawie analizy nagrań wideo. W pracy przedstawiono różne podejścia do problemu oraz utworzono docelowe narzędzie umożliwiające inferencję modelu uczenia maszynowego na nagraniach zamieszczonych przez użytkownika końcowego w celu oceny prawdomówności.

        W badaniach wykorzystano dwa zbiory danych: Silesian Deception Detection Dataset oraz Real-Life Deception Detection Dataset. Do ekstrakcji cech z nagrań wideo, takich jak punkty charakterystyczne twarzy, przepływ optyczny, prawdopodobieństwa wystąpienia emocji, zastosowano narzędzia z bibliotek: MediaPipe, OpenCV, FacialEmotionRecognition.

        Rozważono trzy podejścia modelowe: klasyczny algorytm uczenia maszynowego Random Forest, trójwymiarową sieć neuronową konwolucyjną 3D-CNN oraz finalnie wybraną dwukierunkową sieć rekurencyjną GRU z mechanizmem atencji. W procesie uczenia wykorzystano ekstensywną inżynierię cech oraz technikę transfer learningu (uczenie na jednym zbiorze i dotrenowanie na drugim) w celu poprawy zdolności generalizacji modelu.

        Przeprowadzone eksperymenty wykazały, że model Random Forest pozwolił na identyfikację kluczowych cech behawioralnych, towarzyszących kłamstwu (np. ruchy oczu), natomiast sieć rekurencyjna osiągnęła obiecujące wyniki w analizie sekwencji czasowych, finalnie uzyskując AUC na poziomie 0.63 na zbiorze Silesian Deception Detection Dataset, co znacznie przewyższa zdolności przeciętnego człowieka.

        Integralną częścią pracy jest aplikacja webowa oparta na frameworku Streamlit, pozwalająca użytkownikowi na wgranie pliku wideo i otrzymanie predykcji modelu.

        Wyniki badań sugerują, że metody wizji komputerowej mogą wspomagać proces oceny wiarygodności wypowiedzi, jednak potencjalne praktyczne zastosowania wymagają bardzo dużo reprezentatywnych danych treningowych wysokiej jakości.
      ]
    ),
    keywords: (
      en: ("computer vision", "neural networks", "video processing", "truthfulness assessment", "model training", "artificial intelligence", "deep learning"),
      pl: ("wizja komputerowa", "sieci neuronowe", "przetwarzanie video", "ocena prawdomówności", "trening modeli", "sztuczna inteligencja")
    ),
  )

  // --- Custom Settings ---
  // if you want to override any settings from the template here is the place to do so,
  // e.g.:
  // set text(font: "Comic Sans MS")


  // --- Main Chapters ---
  // include "content/Tutorial.typ" // Some trivial, but useful snippets
  include "content/Introduction.typ"
  include "content/LiteratureReview.typ"
  include "content/Data.typ"
  include "content/Implementation.typ"
  include "content/Website.typ"
  // include "content/Analysis.typ"
  // include "content/Conclusion.typ"

  // --- Acknowledgements ---
  // You can put your acknowledgements (pol. podziękowania) here.
  // Below is an example containing acknowledgements for the PLGrid grant.
  // Comment out if not needed.
  // acknowledgements[
  //   We gratefully acknowledge Poland's high-performance Infrastructure PLGrid
  //   #text(fill: red)[(wybierz właściwy ośrodek z listy: ACK Cyfronet AGH, PCSS, CI TASK,
  //     WCSS)] for providing computer facilities and support within computational grant no
  //   #text(fill: red)[(numer grantu)]
  //   #todo[Numer grantu i typ ośrodka]
  // ]

  // --- Bibliography ---
  bibliography("items.bib", style: "ieee")

  // List of Acronyms - comment out, if not needed (no abbreviations were used).
  glossary-outline(glossary)

  // List of figures - comment out, if not needed.
  figure-outline()

  // List of tables - comment out, if not needed.
  table-outline()

  // --- Appendices ---
  // Comment out if not needed.
  // appendix(lang.thesis, include "content/Appendix.typ")

  if draft {
    set heading(numbering: none)
    note-outline(title: "TODOs")
  }
}
